apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/haoran-openshift-tenant/devfile-sample-python-basic/devfile-sample-python-basic@sha256:b99f1d86ec5360b8a96ee410d25278fa033d8d311cc99b40a1b0ec292651c9f1
        name: my-python
        resources: {}
status: {}
