apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic
    app.kubernetes.io/part-of: devfile-sample-python-basic
  name: devfile-sample-python-basic
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/haoran-openshift-tenant/devfile-sample-python-basic/devfile-sample-python-basic@sha256:b99f1d86ec5360b8a96ee410d25278fa033d8d311cc99b40a1b0ec292651c9f1
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
